### ISSUE TITLE
tflite runmodelonframe error

### ISSUE THREAD

**Issue by DhiraPT** [seriesoftubes/preboot_screenreader#10]
E/RenderScript(22127): Failed loading RS driver: dlopen failed: library "libRSDriverArm.so" not found
E/RenderScript(22127): Failed to load runtime libRSDriverArm.so, loading default

**Comment by creativepsyco** [comment]
which phone/emulator this is happening. I ran this locally on both android emulator (x86) and Pixel 2 debug device (running SDK 30) and it was working fine. A bit slow but did not have anything in the logs that point to a native library not being present.

Are you using vscode or Android studio to develop the app?
