### ISSUE TITLE
camera: ^0.6.4+5 not working

### ISSUE THREAD

**Issue by DhiraPT** [seriesoftubes/preboot_screenreader#6]
currenly using camera ^0.5.8+17
camera: ^0.6.4+5 produces black screen preview

**Comment by creativepsyco** [comment]
Is this using the code in the repo?

**Comment by creativepsyco** [comment]
I tested this with the PR i filed and it works fine.

Video attached

https://user-images.githubusercontent.com/547235/104422698-0fa8db80-55b8-11eb-9172-aa18c0f74375.mp4
